//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xj.MSSQL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCIJournalEntities : DbContext
    {
        public SCIJournalEntities()
            : base("name=SCIJournalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Journal> Journals { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<ArticleAffiliation> ArticleAffiliations { get; set; }
        public DbSet<Author> Authors { get; set; }
        public DbSet<Affiliation> Affiliations { get; set; }
        public DbSet<ArticleAuthor> ArticleAuthors { get; set; }
        public DbSet<JournalIssue> JournalIssues { get; set; }
        public DbSet<Article> Articles { get; set; }
    }
}
